apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
  labels:
    app: kafka
    component: broker
spec:
  # This makes the service "headless".
  clusterIP: None
  ports:
    - name: broker
      port: 9092
      protocol: TCP
    - name: client
      port: 9094
      protocol: TCP
  # This selector must match the labels on the broker pods.
  selector:
    app: kafka
    component: broker
