apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
  namespace: kafka
data:
  client.properties: |
    # Point to the bootstrap service defined in kafka-bootstrap-service.yaml
    bootstrap.servers=kafka-bootstrap.kafka.svc.cluster.local:9094
    # Use SSL for security
    security.protocol=SSL
    # Client's truststore to verify the broker's identity
    ssl.truststore.location=/etc/kafka-client/secrets/kafka.truststore.jks
    ssl.truststore.password=install123!
    # Client's keystore for its own identity (for mTLS)
    ssl.keystore.location=/etc/kafka-client/secrets/client.keystore.jks
    ssl.keystore.password=install123!
    ssl.key.password=install123!
