apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-controller
  namespace: kafka
  labels:
    app: kafka
    component: controller
spec:
  serviceName: kafka-controller-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
      component: controller
  template:
    metadata:
      labels:
        app: kafka
        component: controller
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: config-initializer
          image: busybox:1.36
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              while [ ! -f /config-template/server.properties ]; do
                echo "Waiting for ConfigMap file to be mounted..."
                sleep 1
              done
              echo "ConfigMap mounted. Proceeding with initialization."

              mkdir -p /processed-config
              ORDINAL=${HOSTNAME##*-}
              echo "Initializing config for controller node: $ORDINAL"
              sed -e "s/CONTROLLER_ID_PLACEHOLDER/$ORDINAL/g" \
                  -e "s/SSL_PASSWORD_PLACEHOLDER/${KAFKA_SSL_PASSWORD}/g" \
                  /config-template/server.properties > /processed-config/server.properties
          volumeMounts:
            - name: config-template
              mountPath: /config-template
            - name: processed-config
              mountPath: /processed-config
            - name: tmp
              mountPath: /tmp
          env:
            - name: KAFKA_SSL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-ssl-password
                  key: password
        - name: prepare-storage
          image: apache/kafka:3.9.1
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              TEMP_PROPS_FILE="/tmp/kraft-storage.properties"
              ORDINAL=${HOSTNAME##*-}
              
              cat <<EOF > "$TEMP_PROPS_FILE"
              process.roles=controller
              node.id=$ORDINAL
              log.dirs=/kafka/controller-logs
              controller.listener.names=CONTROLLER
              listeners=CONTROLLER://:9093
              controller.quorum.voters=0@kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9093,1@kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9093,2@kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9093
              EOF

              echo "Formatting storage directory for controller node: $ORDINAL..."
              /opt/kafka/bin/kafka-storage.sh format \
                -t "$KAFKA_CLUSTER_ID" \
                -c "$TEMP_PROPS_FILE" \
                --ignore-formatted
          env:
            - name: KAFKA_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-cluster-config
                  key: cluster.id
            # Override default GC file logging to a writable path.
            - name: KAFKA_GC_LOG_OPTS
              value: "-Xlog:gc*:file=/tmp/kafkaServer-gc.log:time,tags:filecount=10,filesize=100M"
            - name: KAFKA_JVM_PERFORMANCE_OPTS
              value: "-Xlog:gc*:file=/tmp/kafkaServer-gc.log:time,tags:filecount=10,filesize=100M"
          volumeMounts:
            - name: controller-logs
              mountPath: /kafka/controller-logs
            - name: tmp
              mountPath: /tmp
            - name: kafka-logs
              mountPath: /opt/kafka/logs
      containers:
        - name: kafka-controller
          image: apache/kafka:3.9.1
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          command:
            - "/opt/kafka/bin/kafka-server-start.sh"
            - "/processed-config/server.properties"
          ports:
            - containerPort: 9093
              name: controller
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx1G -Xms1G"
            - name: KAFKA_GC_LOG_OPTS
              value: "-Xlog:gc*:file=/tmp/kafkaServer-gc.log:time,tags:filecount=10,filesize=100M"
            - name: KAFKA_JVM_PERFORMANCE_OPTS
              value: "-Xlog:gc*:file=/tmp/kafkaServer-gc.log:time,tags:filecount=10,filesize=100M"
          volumeMounts:
            - name: controller-logs
              mountPath: /kafka/controller-logs
            - name: processed-config
              mountPath: /processed-config
            - name: controller-secrets
              mountPath: /etc/kafka/secrets
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: kafka-logs
              mountPath: /opt/kafka/logs
      volumes:
        - name: config-template
          configMap:
            name: kafka-controller-config
        - name: processed-config
          emptyDir: {}
        - name: controller-secrets
          secret:
            secretName: kafka-controller-secrets
        - name: tmp
          emptyDir: {}
        - name: kafka-logs
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: controller-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
